version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-blog"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6e3lpux9osx"
s3_prefix = "sam-blog"
region = "ca-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
